name: Pull Request Test

on:
  pull_request:
    branches: [main]

jobs:
  pr-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv and sync dev dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.6.0/uv-installer.sh | sh
          uv sync --extra dev
      - name: Run tests
        run: |
          pytest
