name: Version and Tag

on:
  push:
    branches: [main]

jobs:
  version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv and sync dev dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/0.6.0/uv-installer.sh | sh
          uv sync --extra dev
      - name: Bump version and tag using commitizen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cz bump --yes --changelog
          git push --follow-tags
