[project]
name = "gte-py"
version = "0.1.0"
authors = [
    { name = "Jakku Sakura", email = "jakku.sakura@auros.global" }
]
description = "A short description of the project"
entrypoint = "gte_py.main:run"
dependencies = [
    "typer>=0.9.0",
    "aiohttp>=3.8.0",
    "web3~=7.10.0",
    "urllib3~=1.26"
]
dev-dependencies = [
    "rich>=14.0.0",
    "dotenv>=0.9.9",
    "tabulate"
]
[tool.container]
base_image = "python:3.10-slim"
