name: Bump Version

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install uv and sync dev dependencies
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/latest/download/uv-installer.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv sync --extra dev

      - name: Create version-bump branch
        run: |
          git checkout -b bump-version-${{ github.run_number }}
      - name: Bump version and tag using commitizen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          uv run cz bump --yes --changelog
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: bump-version-${{ github.run_number }}
          title: "chore: bump version"
          body: "Automated version bump PR generated by GitHub Actions."
          commit-message: "chore: bump version"
          labels: |
            automated
